name: Daily Siksha Crawler

on:
  workflow_dispatch: # 깃헙 웹페이지에서 수동으로 버튼 눌러서 실행 가능
  schedule:
    - cron: '0 20 * * *' # 매일 한국 시간 새벽 5시(UTC 20:00)에 자동 실행

jobs:
  crawl-and-send:
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드를 가져옵니다 (Checkout)
      uses: actions/checkout@v4

    - name: 파이썬을 설치합니다
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 필요한 라이브러리를 설치합니다
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz

    - name: 🍽️ 학생회관 크롤러 실행
      env:
        CRAWLER_API_KEY: ${{ secrets.CRAWLER_API_KEY }}
      run: python snuco_api_sender.py

    - name: 🍽️ 기숙사 식당 크롤러 실행
      env:
        CRAWLER_API_KEY: ${{ secrets.CRAWLER_API_KEY }}
      run: python snudorm_api_sender.py

    - name: 🍽️ 수의대 식당 크롤러 실행
      env:
        CRAWLER_API_KEY: ${{ secrets.CRAWLER_API_KEY }}
      run: python vet_api_sender.py